[package]
name = "nereon"
description = "Riboseinc configuration library for Rust"
version = "0.1.5"
authors = ["John Hedges <john@drystone.co.uk>"]
license = "BSD-2-Clause"
repository = "https://github.com/riboseinc/rust-nereon"
readme = "README.md"

exclude = ["/**/*~"]

[dependencies]
getopts = "0.2"
regex = "0.2"
serde_json = "1.0"
libc = "0.2"