[package]
name = "nereon"
description = "Riboseinc configuration library for Rust"
version = "0.1.8"
authors = ["John Hedges <john@drystone.co.uk>"]
license = "BSD-2-Clause"
repository = "https://github.com/riboseinc/rust-nereon"
readme = "README.md"

exclude = ["/**/*~"]

[workspace]
members = ["noc"]

[dependencies]
getopts = "0.2"
lazy_static = "1.1"
libc = "0.2"
pest = "1.0"
pest_derive = "*"
regex = "0.2"
serde_json = "1.0"
