[package]
name = "noc"
description = "NOC syntax checker and playground server"
authors = ["John Hedges <john@drystone.co.uk>"]
repository = "https://github.com/riboseinc/rust-nereon"
version = "0.1.0"
license = "BSD-2-Clause"
exclude = ["/**/*~", "/**/.dir-locals.el"]

[dependencies]
nereon = { path = ".." }
nereon_derive = { path = "../derive" }
tiny_http = "0.6"
